'use client';
import Link from 'next/link'; import {usePathname} from 'next/navigation'; import {ChevronRight, Menu, X, Sparkles, CircleUserRound} from 'lucide-react'; import {useState} from 'react'; import {nav} from '@/lib/data';
export function Button({children,href,onClick,variant='primary',className=''}:{children:React.ReactNode;href?:string;onClick?:()=>void;variant?:'primary'|'secondary'|'ghost';className?:string}){const c=`focus-ring inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition hover:-translate-y-0.5 ${variant==='primary'?'bg-blue text-white shadow-glow hover:bg-blue/90':variant==='secondary'?'surface text-white hover:border-blue/60':'text-soft hover:bg-white/5'} ${className}`;return href?<Link className={c} href={href}>{children}</Link>:<button onClick={onClick} className={c}>{children}</button>}
export function Badge({children,color='blue'}:{children:React.ReactNode;color?:string}){return <span className={`rounded-full border border-${color}/30 bg-${color}/10 px-2.5 py-1 text-[11px] font-semibold text-${color}`}>{children}</span>}
export function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={`surface rounded-2xl ${className}`}>{children}</div>}
export function ProgressBar({value,color='bg-blue'}:{value:number|string;color?:string}){return <div className="bar"><span className={color} style={{width:`${Math.min(100,Number(value))}%`}}/></div>}
export function SectionHeader({eyebrow,title,copy,action}:{eyebrow?:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="mb-6 flex items-end justify-between gap-4"><div>{eyebrow&&<p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-blue">{eyebrow}</p>}<h2 className="text-2xl font-semibold tracking-tight">{title}</h2>{copy&&<p className="mt-2 max-w-xl text-sm text-soft">{copy}</p>}</div>{action}</div>}
export function AppShell({children,title}:{children:React.ReactNode;title?:string}){const path=usePathname();const [open,setOpen]=useState(false);return <div className="min-h-screen bg-ink"><aside className={`fixed inset-y-0 left-0 z-30 w-64 border-r border-line bg-[#0b1019] p-5 transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="mb-10 flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-lg font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue text-sm">A</span>ALGA <span className="text-blue">IELTS</span></Link><button className="lg:hidden" onClick={()=>setOpen(false)}><X size={18}/></button></div><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-soft">Workspace</p><nav className="space-y-1">{nav.map(([label,url])=>{const active=path===url||(url!=='/dashboard'&&path.startsWith(url));return <Link onClick={()=>setOpen(false)} key={url} href={url} className={`focus-ring flex items-center rounded-lg px-3 py-2.5 text-sm transition ${active?'bg-blue/15 font-semibold text-white':'text-soft hover:bg-white/5 hover:text-white'}`}><span className="mr-3 h-1.5 w-1.5 rounded-full bg-current opacity-60"/>{label}{active&&<ChevronRight className="ml-auto" size={14}/>}</Link>})}</nav><div className="absolute bottom-6 left-5 right-5 rounded-xl border border-blue/20 bg-blue/10 p-4"><Sparkles size={16} className="mb-2 text-blue"/><p className="text-xs font-semibold">Your next best step</p><p className="mt-1 text-xs text-soft">Improve True / False questions.</p></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-line bg-ink/90 px-5 backdrop-blur-md lg:px-10"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu size={21}/></button><div className="hidden text-sm text-soft lg:block">{title||'Your learning workspace'}</div><div className="ml-auto flex items-center gap-5"><div className="hidden text-right sm:block"><p className="text-xs text-soft">Target band</p><p className="text-sm font-semibold">7.5 <span className="ml-2 text-mint">↗ 6 day streak</span></p></div><CircleUserRound className="text-blue" size={27}/></div></header><main className="mx-auto max-w-[1500px] p-5 lg:p-10">{children}</main></div></div>}
export function StatCard({label,value,meta,trend}:{label:string;value:string;meta:string;trend?:string}){return <Card className="p-5"><p className="text-xs font-medium text-soft">{label}</p><div className="mt-3 flex items-end justify-between"><p className="text-3xl font-semibold tracking-tight">{value}</p>{trend&&<span className="text-xs text-mint">{trend}</span>}</div><p className="mt-2 text-xs text-soft">{meta}</p></Card>}
